language: python
install: "pip install requests"
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
env:
  - CI=true
  - TRAVIS=true
# command to install dependencies
# command to run tests
script: python ANDAI.py
